Port = 31000
APIPort = 58000
KeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
ObseverPort = 35000
FormulatorPort = 37000
StoreRoot = "./observer"
ForceRecover = true

[ObserverKeyMap]
3e5PNobd577YEdjeb59zG6N7BBZbyRKMja2s55QQMQE = "testnet_observer1.fleta.io:35000"
4ry8UmsCbo1BPTmUhqjMWgy9UtLDFcebEsc4Lgjo9ba = "testnet_observer2.fleta.io:35000"
4KT4crmdp5GDihPXufUonmAujjC1YH4viej8C1udjc4 = "testnet_observer3.fleta.io:35000"
3suqtMQWdUFUwDGMzH53KRJPFzqaP6YYRqRGMPLhhp5 = "testnet_observer4.fleta.io:35000"
3HLUjZYeUDc7nGKqCaRyqB8yJHwj3BgFMWUYNmMSYfE = "testnet_observer5.fleta.io:35000"
