Port = 31000
APIPort = 58000
KeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
ObseverPort = 35000
FormulatorPort = 37000
StoreRoot = "./odata"
ForceRecover = true

[ObserverKeyMap]
3UwhKPR25vZyycKXzvTjTTEvaQhLYNdga7Qfu96nkFS = "observer1.fletamain.net:35000"
3LRTWd7Gsjx6nLtyPewi5z1wkMGMT4GDYwnkYWFwDjx = "observer2.fletamain.net:35000"
6NCt1mLHxVSQYrSLJv5QmRWh236eEfw6jUMXAGURBN = "observer3.fletamain.net:35000"
4Muu1gBArNvekXNF5CNSJhRFq31xPejb6kQ8Js1jwRA = "observer4.fletamain.net:35000"
nnyPSWrxKXpozLZ36u9dEM9yH5mna2jk4oq6hCAZ8c = "observer5.fletamain.net:35000"
