Port = 31000
APIPort = 58000
GenKeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
Formulator = "THIS_IS_A_ADDRESS_OF_THE_FORMULATOR"
StoreRoot = "./fdata"
Backend = "badger"
RLogHost = ""
RLogPath = ""
UseRLog = false

[ObserverKeyMap]
3UwhKPR25vZyycKXzvTjTTEvaQhLYNdga7Qfu96nkFS = "observer1.fletamain.net"
3LRTWd7Gsjx6nLtyPewi5z1wkMGMT4GDYwnkYWFwDjx = "observer2.fletamain.net"
6NCt1mLHxVSQYrSLJv5QmRWh236eEfw6jUMXAGURBN = "observer3.fletamain.net"
4Muu1gBArNvekXNF5CNSJhRFq31xPejb6kQ8Js1jwRA = "observer4.fletamain.net"
nnyPSWrxKXpozLZ36u9dEM9yH5mna2jk4oq6hCAZ8c = "observer5.fletamain.net"

[SeedNodeMap]
3yTFnJJqx3wCiK2Edk9f9JwdvdkC4DP4T1y8xYztMkf = "seednode1.fletamain.net:31000"
3EjA1hKkfYZ4KL1c4f67CfaNwb9fCqUneiYkyQEhsGi = "seednode2.fletamain.net:31000"
314AUADxjj7nWjeNpR8XEoAh4DdX3ArNHaipPGMFQ4u = "seednode3.fletamain.net:31000"
3n8QNWd7M839ouauhdHvmgmk4NsLj4qGM6tpfoaLNxc = "seednode4.fletamain.net:31000"
