InitGenesisHash = ""
InitHeight = 0
InitHash = ""
InitTimestamp = 0
Port = 22001
RPCPort = 8541
StoreRoot = "./fdata"
GeneratorKeyHex = "GENERATOR_KEY_HEX_HERE"
UseWSS = false
# NodeKeyHex = "NODE_KEY_HEX_HERE"

[ObserverMap]
0471e935c8e1f54f25a6424274ab07e7891873c3b1a27a6c40b805264597a6257f78d93e59f47c22513ded86ba47ae2a52ef2523540cf70f7a5b217461d1b1e582 = "155.138.202.203:21001"
0468ccfa69a56c01169ebfc96b480c285c0261f3e040e4e4aa164843905a2fa876ed037261cc2ed92a6cd485167861c94468470a0545b1eaf56ae68383b4874f3f = "45.32.219.200:21001"
040d8430f8dd73099e5c47e8222c5bc60b80ca9111f72b17576409e92fe139423f1d96c8e67dc32338977bc0a24200589ca3cb352647c44cb437a11d8f7d87d664 = "96.30.192.237:21001"
04137fe73a6de828bc1146a177269f2de60d52fb70ac745dc583abe161ad70fa4d65526a18c25122fab4e11c590e6a624b2aeb72333fe8ee3aba0046600cd002c1 = "155.138.219.116:21001"
04c68eb00038d3794a356c35cae8360642fb6a21bf7d6239e93048992b4a7d9e9014174bc4fdd6810b2bb270ceb141f995d0a3b6adc96f3d53bcd1d9e9745a96ec = "144.202.27.81:21001"

[SeedNodeMap]
04a2b3f2bc8de63d2c237fcd96e42c95caa64501059b928e47882ec6a5dcd98e060a6aeb27b21a152a1edf073c87cc82fa3360ce55e6fe1df4822a234385a4bb2d = "158.247.221.98:22001"
